### ISSUE TITLE
More advanced features similar to Roll-20

### ISSUE THREAD

**Issue by DonaldTsang** [bsredbeard/rolldice#8]
RPG dice rolling function covering more features
Code: https://app.roll20.net/assets/dengine.js?v=123
Mirror: https://ghostbin.com/paste/2n67m
Reference: https://wiki.roll20.net/Dice_Reference

- [ ] addition, subtraction, multiplication, division, modulo, exponentiation
- [ ] floor, round, ceil, abs
    - >Abilities are expanded (meaning the definition of the ability is placed in the formula anywhere that ability appears).
Macros are expanded, including nested macros up to 99 levels deep.
Variables are substituted
Roll queries are executed (the player making the roll is asked to provide a value for each query, and that value is substituted in where the roll query appears in the formula)
All previous steps are repeated until there are no longer any unresolved abilities, macros, variables, or queries. This allows for nesting (e.g. putting an attribute in a macro).
Inline rolls are executed, starting with the most deeply nested inline roll working upward. The overall result of the inline roll is substituted in place where it appeared in the formula.
The remaining roll is executed: first, dice are rolled for any dice (e.g. "2d6" is rolled; including any special dice such as dropped or exploding), then the result of that roll is substituted into the formula. Next, floor() and ceil() functions are executed. Finally, the entire remaining formula is evaluated, including observing proper math order of operations (parentheses first, then multiplication/division, then addition/subtraction).
- [ ] All Types Of Dice
    - [ ] Basic Roll of `NdX`
    - [ ] Fate/Fudge Roll `NdF`
    - [ ] Computed Dice Roll `(N+Y)dX` or `Nd(X+Y)`
- [ ] All Roll Modifiers
    - [ ] Target Number / Successes (B,F) - CP
    - [ ] Failures (B,F) - fCP
    - [ ] Exploding Dice (B,F) !CP
    - [ ] Compounding Dice (B,F) !!CP
    - [ ] Penetrating Dice (B,F) !pCP
    - [ ] Dice Matching `m` and `mt`
    - [ ] Keep / Drop Dice (B,F) `khN` or `klN` or `dhN` `dlN`
    - [ ] Rerolling Dice (B,F) `rCP`
    - [ ] Sorting Dice (B,F) `sa` or `sd`
    - [ ] Order of Operations for Modifiers
        -  >Exploding, Compounding, Penetrating, Rerolls
These are applied while the dice are still rolling. imagine that you roll some exploding 6d6 on your table and the instant one of them settles as a 6 another die is rolled
Keep, Drop, Success, Failure, Sorting
These are applied after all of the dice have "settled" and all of the result values are known.
- [ ] Grouped Rolls
- [ ]  Grouped Roll Modifiers
    - [ ] Keep / Drop `khN` or `klN` or `dhN` or `dlN`
    - [ ]  Target Number / Successes (B,F) `CP`
    - [ ] Failures (B,F) `fCP`

**Comment by bsredbeard** [comment]
Hi @DonaldTsang, are you proposing to add some of these features? I'm unsure why you linked to Roll20's application code.

Many of these features are already in the library, but under different acronyms, and some are a bit outside the scope of what I had hoped to provide to consumers. Check out the library's built in roll `help`, or the special functions javascript file. You can find an interactive demo of the library where you can execute the `help` roll over here: http://bsredbeard.github.io/rolldice/

If you can refine this a bit, perhaps the issue can be handled by a motivated individual who sends a PR my way. Thanks!

**Comment by DonaldTsang** [comment]
@bsredbeard if it is under a different acronym, that would be fine, my worry is that the order of operations will be different, as Roll20 has become a gold standard on dice notation.

**Comment by bsredbeard** [comment]
This library is not something I spend a lot of time on, and I haven't made a commit I'm this codebase in over a year. I'm personally happy with it's functionality, but if you find it deficient, feel free to fork it and send a PR after you've done the work and tested it. That could also be said about the several other libraries you've commented on.
